#!/usr/bin/env bash

# Exit if no arguments supplied
if [ $# -eq 0 ]
  then
    exit 1
fi

PARAMS=$XDG_CONFIG_HOME/rofi/scripts/parameters.json

# Set field separator to tab to exploit jq's tsv output
IFS=$'\t'

# Read Rofi parameters from file
load_rofi_params() {
	FORMAT=$(jq -cr ."$1".format $PARAMS)
    OPTIONS=( $(jq -cr '.'"$1"'.options | @tsv' $PARAMS) )
    ACTIONS=( $(jq -cr '.'"$1"'.actions | @tsv' $PARAMS) )
    CONFIRM=( $(jq -cr '.'"$1"'.confirm | @tsv' $PARAMS) )
	THEME=$(jq -cr ."$1".theme $PARAMS)
}

list_options() {
    for i in "${OPTIONS[@]}"
    do
        echo "$i"
    done
}

execute_action() {
    local OPTION="${OPTIONS[$1]}"
    local CONFIRM="${CONFIRM[$1]}"

    if $CONFIRM; then
        if $XDG_CONFIG_HOME/rofi/scripts/rofi_confirm $OPTION; then
            eval "${ACTIONS[$1]}"
        fi
    else
        eval "${ACTIONS[$1]}"
    fi
}

rofi_dmenu() {
    # NOTE: 'rofi -format i' returns a zero-ordered index of the selected option
    list_options | rofi -dmenu -theme "$THEME" -format "$FORMAT"
}

# Script execution starts here
if [ "${1}" != "--source-only" ]; then
    load_rofi_params $1

    SELECTION="$(rofi_dmenu)"

    if [[ $SELECTION ]]; then
        execute_action $SELECTION &
    else
        exit 1
    fi
fi

